/* =============================================================================
CASE STUDY #2: PIZZA RUNNER
SECTION A: PIZZA METRICS
=============================================================================

--- KEY INSIGHTS ---
1. PEAK ORDER HOURS: THE HIGHEST ORDER VOLUMES OCCUR AT 13:00 (1 PM) 
   AND 21:00 (9 PM), EACH RECORDING 3 ORDERS.
2. WEEKLY DEMAND: WEDNESDAY AND SATURDAY ARE THE BUSIEST DAYS OF THE WEEK 
   WITH 5 PIZZAS ORDERED ON EACH DAY.
=============================================================================
*/

-- 1: HOW MANY PIZZAS WERE ORDERED?
SELECT COUNT(*) AS TOTAL_PIZZA_ORDERED 
FROM CUSTOMER_ORDERS;


-- 2: HOW MANY UNIQUE CUSTOMER ORDERS WERE MADE?
SELECT COUNT(DISTINCT ORDER_ID) AS UNIQUE_CUSTOMERS 
FROM CUSTOMER_ORDERS;


-- 3: HOW MANY SUCCESSFUL ORDERS WERE DELIVERED BY EACH RUNNER?
SELECT RUNNER_ID, COUNT(ORDER_ID) AS SUCCESSFUL_DELIVERIES
FROM RUNNER_ORDERS
WHERE CANCELLATION IS NULL
GROUP BY RUNNER_ID;


-- 4: HOW MANY OF EACH TYPE OF PIZZA WAS DELIVERED?
SELECT PN.PIZZA_NAME, COUNT(CO.PIZZA_ID) AS DELIVERED_COUNT
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID
JOIN PIZZA_NAMES AS PN ON CO.PI_ID = PN.PIZZA_ID
WHERE RO.CANCELLATION IS NULL
GROUP BY PN.PIZZA_NAME;


-- 5: HOW MANY VEGETARIAN AND MEATLOVERS WERE ORDERED BY EACH CUSTOMER?
-- NOTE: USING SUM(CASE...) TO PIVOT DATA INTO COLUMNS
SELECT CUSTOMER_ID,
    SUM(CASE WHEN PIZZA_ID = 1 THEN 1 ELSE 0 END) AS MEATLOVERS,     
    SUM(CASE WHEN PIZZA_ID = 2 THEN 1 ELSE 0 END) AS VEGETARIAN
FROM CUSTOMER_ORDERS
GROUP BY CUSTOMER_ID;


-- 6: WHAT WAS THE MAXIMUM NUMBER OF PIZZAS DELIVERED IN A SINGLE ORDER?
SELECT CO.ORDER_ID, COUNT(CO.PIZZA_ID) AS MAX_PIZZAS
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID
WHERE RO.CANCELLATION IS NULL
GROUP BY CO.ORDER_ID
ORDER BY MAX_PIZZAS DESC 
LIMIT 1; 


-- 7: FOR EACH CUSTOMER, HOW MANY DELIVERED PIZZAS HAD AT LEAST 1 CHANGE AND HOW MANY HAD NO CHANGES?
SELECT CO.CUSTOMER_ID, 
    SUM(CASE WHEN EXCLUSIONS IS NULL AND EXTRAS IS NULL THEN 1 ELSE 0 END) AS NO_CHANGE,
    SUM(CASE WHEN EXCLUSIONS IS NOT NULL OR EXTRAS IS NOT NULL THEN 1 ELSE 0 END) AS CHANGES
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID
WHERE RO.CANCELLATION IS NULL
GROUP BY CO.CUSTOMER_ID;


-- 8: HOW MANY PIZZAS WERE DELIVERED THAT HAD BOTH EXCLUSIONS AND EXTRAS?
-- NOTE: USING 'AND' TO ENSURE BOTH CONDITIONS ARE MET SIMULTANEOUSLY
SELECT 
    SUM(CASE WHEN EXCLUSIONS IS NOT NULL AND EXTRAS IS NOT NULL THEN 1 ELSE 0 END) AS BOTH_CHANGES
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID
WHERE RO.CANCELLATION IS NULL;


-- 9: WHAT WAS THE TOTAL VOLUME OF PIZZAS ORDERED FOR EACH HOUR OF THE DAY?
SELECT HOUR(ORDER_TIME) AS HOURLY_ORDERS, COUNT(PIZZA_ID) AS PIZZA_COUNT
FROM CUSTOMER_ORDERS
GROUP BY HOURLY_ORDERS
ORDER BY HOURLY_ORDERS;


-- 10: WHAT WAS THE VOLUME OF ORDERS FOR EACH DAY OF THE WEEK?
SELECT DAYNAME(order_time) AS ORDERS_BY_DAY, COUNT(PIZZA_ID) AS PIZZA_COUNT
FROM CUSTOMER_ORDERS
GROUP BY DAYNAME(ORDER_TIME)
ORDER BY PIZZA_COUNT DESC;
