/* -------------------------------------------------------
PIZZA RUNNER CASE STUDY: SECTION B
RUNNER AND CUSTOMER EXPERIENCE
-------------------------------------------------------
*/

-- B1: HOW MANY RUNNERS SIGNED UP FOR EACH 1 WEEK PERIOD?

SELECT 
    FLOOR(DATEDIFF(REGISTRATION_DATE, '2021-01-01') / 7) + 1 AS REGISTRATION_WEEK, 
    COUNT(RUNNER_ID) AS TOTAL_RUNNER_SIGNUPS
FROM RUNNERS
GROUP BY REGISTRATION_WEEK;


-- B2: WHAT WAS THE AVERAGE TIME (MINS) FOR RUNNERS TO ARRIVE AT PIZZA RUNNER HQ FOR PICKUP?

WITH ARRIVAL_TIME_CTE AS (
    SELECT 
        RO.RUNNER_ID, 
        TIMESTAMPDIFF(MINUTE, CO.ORDER_TIME, RO.PICKUP_TIME) AS PREP_AND_ARRIVAL_TIME
    FROM CUSTOMER_ORDERS AS CO
    JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID
    WHERE RO.CANCELLATION IS NULL
)
SELECT 
    RUNNER_ID, 
    ROUND(AVG(PREP_AND_ARRIVAL_TIME), 2) AS AVG_PICKUP_ARRIVAL_MINUTES
FROM ARRIVAL_TIME_CTE
GROUP BY RUNNER_ID;


-- B3: IS THERE ANY RELATIONSHIP BETWEEN NUMBER OF PIZZAS AND HOW LONG THE ORDER TAKES TO PREPARE?

WITH ORDER_METRICS_CTE AS (
    SELECT 
        RO.ORDER_ID, 
        COUNT(CO.PIZZA_ID) AS PIZZA_COUNT, 
        TIMESTAMPDIFF(MINUTE, MAX(CO.ORDER_TIME), MAX(RO.PICKUP_TIME)) AS TOTAL_PREP_TIME
    FROM CUSTOMER_ORDERS AS CO
    JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID 
    WHERE RO.CANCELLATION IS NULL
    GROUP BY RO.ORDER_ID
)
SELECT 
    PIZZA_COUNT, 
    ROUND(AVG(TOTAL_PREP_TIME), 2) AS AVG_TOTAL_PREP_TIME,
    ROUND(AVG(TOTAL_PREP_TIME / PIZZA_COUNT), 1) AS AVG_PREP_TIME_PER_PIZZA
FROM ORDER_METRICS_CTE
GROUP BY PIZZA_COUNT;


-- B4: WHAT WAS THE AVERAGE DISTANCE TRAVELLED FOR EACH CUSTOMER?

SELECT 
    CO.CUSTOMER_ID, 
    ROUND(AVG(RO.DISTANCE_KM), 2) AS AVG_DELIVERY_DISTANCE_KM
FROM CUSTOMER_ORDERS AS CO
JOIN RUNNER_ORDERS AS RO ON CO.ORDER_ID = RO.ORDER_ID
WHERE RO.CANCELLATION IS NULL
GROUP BY CO.CUSTOMER_ID;


-- B5: WHAT WAS THE DIFFERENCE BETWEEN THE LONGEST AND SHORTEST DELIVERY TIMES FOR ALL ORDERS?

SELECT 
    MAX(DURATION_MIN) - MIN(DURATION_MIN) AS DELIVERY_DURATION_SPREAD_MINS
FROM RUNNER_ORDERS
WHERE DURATION_MIN IS NOT NULL;


-- B6: WHAT WAS THE AVERAGE SPEED FOR EACH RUNNER PER DELIVERY FOR EACH DELIVERY AND DO YOU NOTIVE ANY TREND FOR THESE VALUES?
-- INSIGHT: SPEED INCREASES WITH DISTANCE. ORDER #8 IS A MAJOR OUTLIER (93.6 KM/H), 
-- SUGGESTING EITHER RECKLESS DRIVING OR A DATA ENTRY ERROR IN DURATION.

WITH SPEED_CALCULATION_CTE AS (
    SELECT 
        RUNNER_ID,
        ORDER_ID,
        DISTANCE_KM, 
        (DISTANCE_KM / (DURATION_MIN / 60.0)) AS CALCULATED_SPEED_KMH
    FROM RUNNER_ORDERS
    WHERE CANCELLATION IS NULL
)
SELECT 
    RUNNER_ID, 
    ORDER_ID, 
    DISTANCE_KM, 
    ROUND(AVG(CALCULATED_SPEED_KMH), 2) AS AVG_SPEED_KMH
FROM SPEED_CALCULATION_CTE
GROUP BY RUNNER_ID, ORDER_ID, DISTANCE_KM
ORDER BY RUNNER_ID, DISTANCE_KM;


-- B7: WHAT IS THE SUCCESSFUL DELIVERY PERCENTAGE FOR EACH RUNNER?

WITH DELIVERY_STATS_CTE AS (
    SELECT 
        RUNNER_ID, 
        SUM(CASE WHEN CANCELLATION IS NULL THEN 1 ELSE 0 END) AS SUCCESSFUL_DELIVERIES,
        COUNT(*) AS TOTAL_ASSIGNED_ORDERS
    FROM RUNNER_ORDERS
    GROUP BY RUNNER_ID
)
SELECT 
    RUNNER_ID, 
    ROUND((SUCCESSFUL_DELIVERIES * 100.0 / TOTAL_ASSIGNED_ORDERS), 0) AS SUCCESS_RATE_PERCENT
FROM DELIVERY_STATS_CTE;
