-- ============================================================
-- SECTION A: HIGH LEVEL SALES ANALYSIS
-- ============================================================

-- 1: What was the total quantity sold for all products?
SELECT SUM(qty) AS total_items_sold 
FROM sales;
-- Result: 45216 items sold in three months

-- 2: What is the total generated revenue for all products before discounts?
SELECT SUM(qty * price) AS total_revenue 
FROM sales;
-- Result: 1289453 total revenue generated by calculating qty * price without any discount

-- 3: What was the total discount amount for all products?
-- discount column is a percentage so actual discount = qty * price * discount / 100
SELECT ROUND(SUM(qty * price * (discount / 100)), 2) AS total_discount
FROM sales;
-- Result: 156229.14 total discount amount across all products
