-- ============================================================
-- SECTION A: HIGH LEVEL SALES ANALYSIS
-- ============================================================

-- 1: What was the total quantity sold for all products?
SELECT SUM(qty) AS total_items_sold 
FROM sales;
-- Result: 45216 items sold in three months

-- 2: What is the total generated revenue for all products before discounts?
SELECT SUM(qty * price) AS total_revenue 
FROM sales;
-- Result: 1289453 total revenue generated by calculating qty * price without any discount
